"""empty message

Revision ID: 00701bdef562
Revises: None
Create Date: 2017-10-15 23:34:28.401256

"""

# revision identifiers, used by Alembic.
revision = '00701bdef562'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trained_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trained_models')
    # ### end Alembic commands ###
