version: '3'
services:
  db:
    image: postgres

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./web:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

  tensorflow-serving:
    image: 'bitnami/tensorflow-serving:latest'
    ports:
      - 9000:9000
    volumes:
      - 'tensorflow_serving_data:/bitnami'
      - './tmp/model-data:/bitnami/model-data'

  tensorflow-inception:
    image: 'bitnami/tensorflow-inception:latest'
    depends_on:
      - tensorflow-serving
    volumes:
      - 'tensorflow_inception_data:/bitnami'
      - './tmp/model-data:/bitnami/model-data'
      - './tmp/input:/bitnami/input'

volumes:
  tensorflow_serving_data:
    driver: local
  tensorflow_inception_data:
    driver: local
