version: '3'
services:
  redis:
    image: "redis:alpine"

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    command: python app.py
    volumes:
      - ./app:/code
    ports:
      - "5000:5000"
    depends_on:
      - redis

  tensorflow-serving:
    image: 'bitnami/tensorflow-serving:latest'
    ports:
      - 9000:9000
    volumes:
      - 'tensorflow_serving_data:/bitnami'
      - './tmp/model-data:/bitnami/model-data'

  tensorflow-inception:
    image: 'bitnami/tensorflow-inception:latest'
    depends_on:
      - tensorflow-serving
    volumes:
      - 'tensorflow_inception_data:/bitnami'
      - './tmp/model-data:/bitnami/model-data'
      - './tmp/input:/bitnami/input'

volumes:
  tensorflow_serving_data:
    driver: local
  tensorflow_inception_data:
    driver: local
